image: node:18

variables:
    AWS_REGION: ap-south-1

.pre_build: &pre_build
    - npm install --legacy-peer-deps
    - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    - unzip -q awscliv2.zip
    - ./aws/install 

stages:
    - deploy

production:
    stage: deploy
    script:
        - *pre_build 
        - npm run build:production
        - aws s3 sync --delete dist/ss-ai-interview/ s3://interview.supersourcing.com/
        - aws cloudfront create-invalidation --distribution-id E27Q1VMTO1O22J --paths "/*"
    environment: production
    only:
        - main

dev:
    stage: deploy
    script:
        - *pre_build
        - npm run build:development
        - aws s3 sync --delete dist/ss-ai-interview/ s3://devinterview.supersourcing.com/
        - aws cloudfront create-invalidation --distribution-id E1BQ968P0LSWAS --paths "/*"
    environment: dev
    only:
        - develop
